/** Pre-built icon + label snippets for tables, buttons, and menus */
import { icon, iconLg } from './icons.js';

const inl = { size: 14, className: 'ui-icon-inline' };

export const L = {
    edit: `${icon('edit', inl)} Edit`,
    editUser: `${icon('edit', inl)} Edit User`,
    editBatch: `${icon('edit', inl)} Edit Batch`,
    deactivate: `${icon('trash', inl)} Deactivate`,
    cancel: `${icon('trash', inl)} Cancel`,
    newMessage: `${icon('edit', inl)} New Message`,
    send: icon('send'),
    attach: icon('attach', inl),
    link: icon('link', inl),
    warning: icon('warning', inl),
    programs: `${icon('clipboard', inl)} Programs`,
    offerings: `${icon('calendar', inl)} Offerings`,
    manageSections: `${icon('school', inl)} Manage Sections`,
    byInstructor: `${icon('users', inl)} By Instructor`,
    bySubject: `${icon('clipboard', inl)} By Subject`,
    aiGenerate: `${icon('robot', inl)} AI Generate`,
    aiGraded: `${icon('robot', { size: 12, className: 'ui-icon-inline' })} AI Graded`,
    messagesLg: iconLg('messages'),
    quiz: icon('quiz', inl),
    quizLg: iconLg('quiz'),
    editLg: iconLg('edit'),
    users: icon('users', inl),
    usersMd: icon('users', { size: 16 }),
    video: icon('video', { size: 22 }),
    tools: icon('tools', { size: 22 }),
    messages: icon('messages', { size: 16 }),
    messagesInl: icon('messages', inl),
    wave: icon('wave', { size: 20, className: 'ui-icon-inline' }),
    instructor: icon('instructor', { size: 22 }),
    school: icon('school', { size: 22 }),
    schoolInl: icon('school', inl),
    schoolMd: icon('school', { size: 20 }),
    instructorMd: icon('instructor', { size: 20 }),
    event: `${icon('calendar', inl)} Event`,
    hasQuiz: `${icon('quiz', { size: 12, className: 'ui-icon-inline' })} Has Quiz`,
    downloadFile: `${icon('attach', inl)} Download / View File`,
    openLink: `${icon('link', inl)} Open Link`,
    preview: `${icon('preview', inl)} Preview`,
    copyToClass: `${icon('copy', inl)} Copy to My Class`,
    remove: `${icon('trash', inl)} Remove`,
    lessons: `${icon('lessons', inl)} Lessons`,
    lessonsLg: icon('lessons', { size: 20 }),
    book: icon('book', { size: 20 }),
    searchLg: iconLg('search'),
    publishLesson: `${icon('lessons', inl)} Publish Lesson to Bank`,
    unassigned: `${icon('warning', inl)} Unassigned`,
};

export { icon, iconLg };
