<?php
/**
 * One-time Gmail SMTP setup for COC-LMS.
 * Open in browser: http://localhost/COC_LMS(2)/tools/mail-setup.php
 * Localhost only — saves config/email.local.php and sends a test email.
 */
declare(strict_types=1);

$host = $_SERVER['HTTP_HOST'] ?? '';
$isLocal = in_array($host, ['localhost', '127.0.0.1'], true)
    || str_starts_with($host, 'localhost:')
    || str_starts_with($host, '127.0.0.1:');

if (!$isLocal && PHP_SAPI !== 'cli') {
    http_response_code(403);
    echo 'Mail setup is only available on localhost.';
    exit;
}

$localFile = dirname(__DIR__) . '/config/email.local.php';
$message = '';
$messageType = '';
$configured = false;

if (is_file($localFile)) {
    $contents = file_get_contents($localFile);
    $configured = str_contains($contents, '@') && !str_contains($contents, "define('GMAIL_SMTP_USER', '');");
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $gmail = trim($_POST['gmail'] ?? '');
    $appPass = str_replace(' ', '', trim($_POST['app_password'] ?? ''));
    $testTo = trim($_POST['test_to'] ?? $gmail);

    if (!filter_var($gmail, FILTER_VALIDATE_EMAIL)) {
        $message = 'Enter a valid Gmail address.';
        $messageType = 'error';
    } elseif (strlen($appPass) < 16) {
        $message = 'App Password must be 16 characters (from Google → App passwords).';
        $messageType = 'error';
    } elseif (!filter_var($testTo, FILTER_VALIDATE_EMAIL)) {
        $message = 'Enter a valid test recipient email.';
        $messageType = 'error';
    } else {
        $escapedUser = addslashes($gmail);
        $escapedPass = addslashes($appPass);
        $php = <<<PHP
<?php
/**
 * Local Gmail credentials — generated by tools/mail-setup.php
 * Do not commit this file.
 */
if (!defined('GMAIL_SMTP_USER')) {
    define('GMAIL_SMTP_USER', '{$escapedUser}');
}
if (!defined('GMAIL_SMTP_APP_PASSWORD')) {
    define('GMAIL_SMTP_APP_PASSWORD', '{$escapedPass}');
}

PHP;

        if (!file_put_contents($localFile, $php)) {
            $message = 'Could not write config/email.local.php — check folder permissions.';
            $messageType = 'error';
        } else {
            require_once dirname(__DIR__) . '/config/constants.php';
            require_once dirname(__DIR__) . '/config/email.php';
            require_once dirname(__DIR__) . '/api/helpers/GmailSmtpHelper.php';

            $html = '<p style="font-family:sans-serif;">Gmail SMTP is working for <strong>PHINMA COC-LMS</strong>.</p>';
            $text = 'Gmail SMTP is working for PHINMA COC-LMS.';
            $ok = GmailSmtpHelper::send($testTo, 'COC-LMS — Gmail test OK', $html, $text);

            if ($ok) {
                $message = "Saved and test email sent to {$testTo}. You can close this page.";
                $messageType = 'success';
                $configured = true;
            } else {
                $message = 'Credentials saved but send failed. Check App Password and 2-Step Verification, then try again.';
                $messageType = 'error';
            }
        }
    }
}

header('Content-Type: text/html; charset=UTF-8');
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gmail SMTP Setup — COC-LMS</title>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; font-family: 'Segoe UI', system-ui, sans-serif; background: #f4f6f5; display: flex; align-items: center; justify-content: center; padding: 24px; }
    .card { width: 100%; max-width: 480px; background: #fff; border-radius: 16px; box-shadow: 0 8px 32px rgba(0,70,27,.12); overflow: hidden; }
    .head { background: linear-gradient(135deg,#00461B,#1B4D3E); color: #fff; padding: 28px 32px; }
    .head h1 { margin: 0 0 6px; font-size: 20px; }
    .head p { margin: 0; font-size: 13px; opacity: .9; line-height: 1.5; }
    .body { padding: 28px 32px; }
    label { display: block; font-size: 13px; font-weight: 600; color: #374151; margin-bottom: 6px; }
    input { width: 100%; padding: 11px 14px; border: 1px solid #d1d5db; border-radius: 8px; font-size: 14px; margin-bottom: 16px; }
    input:focus { outline: none; border-color: #1B4D3E; box-shadow: 0 0 0 3px rgba(27,77,62,.15); }
    .steps { background: #E8F5E9; border-radius: 10px; padding: 14px 16px; margin-bottom: 20px; font-size: 13px; color: #1B4D3E; line-height: 1.6; }
    .steps a { color: #00461B; font-weight: 600; }
    .steps ol { margin: 8px 0 0; padding-left: 20px; }
    button { width: 100%; padding: 13px; background: #00461B; color: #fff; border: none; border-radius: 8px; font-size: 15px; font-weight: 600; cursor: pointer; }
    button:hover { background: #1B4D3E; }
    .msg { padding: 12px 14px; border-radius: 8px; font-size: 13px; margin-bottom: 16px; line-height: 1.5; }
    .msg.success { background: #E8F5E9; color: #1B4D3E; }
    .msg.error { background: #FEE2E2; color: #991B1B; }
    .badge { display: inline-block; background: rgba(255,255,255,.2); padding: 4px 10px; border-radius: 999px; font-size: 11px; margin-top: 10px; }
  </style>
</head>
<body>
  <div class="card">
    <div class="head">
      <h1>Gmail SMTP Setup</h1>
      <p>Connect COC-LMS to your Gmail account for OTP and notification emails.</p>
      <?php if ($configured): ?>
        <span class="badge">Already configured</span>
      <?php endif; ?>
    </div>
    <div class="body">
      <?php if ($message): ?>
        <div class="msg <?= htmlspecialchars($messageType) ?>"><?= htmlspecialchars($message) ?></div>
      <?php endif; ?>

      <div class="steps">
        <strong>Before you continue — in Google (2 minutes):</strong>
        <ol>
          <li>Open <a href="https://myaccount.google.com/security" target="_blank" rel="noopener">Google Security</a></li>
          <li>Turn on <strong>2-Step Verification</strong></li>
          <li>Search <strong>App passwords</strong> → create one for <strong>Mail</strong></li>
          <li>Copy the 16-character password (e.g. <code>abcd efgh ijkl mnop</code>)</li>
        </ol>
      </div>

      <form method="post">
        <label for="gmail">Gmail address</label>
        <input type="email" id="gmail" name="gmail" placeholder="yourname@gmail.com" required>

        <label for="app_password">Google App Password (16 chars)</label>
        <input type="password" id="app_password" name="app_password" placeholder="xxxx xxxx xxxx xxxx" required autocomplete="off">

        <label for="test_to">Send test email to</label>
        <input type="email" id="test_to" name="test_to" placeholder="Same as Gmail or another inbox">

        <button type="submit">Save &amp; send test email</button>
      </form>
    </div>
  </div>
</body>
</html>
